version: "3"

services:
  frontend:
    build: ./frontend
    container_name: real-world-docker-frontend
    command: serve -s biuld -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  api:
    build: ./api
    container_name: real-world-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://real-world-docker.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: real-world-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://real-world-docker.com
      - MONGO_URL=mongodb://auth_db:27017/api
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: real-world-docker-api-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: real-world-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

volumes:
  mongodb_api:
  mongodb_auth:
